### PR TITLE
Fix: Time-based tracking fix for ASP

### PR DESCRIPTION
**Pull request by darth3pio**
These changes fix the error that gets thrown when attempting to view player details in Private Stats Admin.

### CODE REVIEW

**Comment by darth3pio** [comment]
If you look at older commits from Wilson212, The feature was already there, it was one of the community members of the BF2Statistics forums that suggested removing $time from the selectunlock.php funtion as they couldn't figure out the issue they were looking at. It was two things a) Unlocks weren't unlocking and b) Viewing player pages in Private Stats Admin would throw an error when the time had to be formatted.

It's tricky to separate the two as they both rely on each other at least if you want to run it on a newer PHP version.

Viewing a player page (PlayerModel.php) still heavily queried $time so without commenting out everything it wouldn't actually fix that issue.

I narrowed it down to

1) The reason unlocks hadn't been unlocking was because the timespan column didn't exist so I updated the schema.sql to add it in when the db was generated. (Removing $time from selectunlock.php was a bandaid fix)
2) This also required that selectunlock.php actually generate a timestamp to enter into the database when you select an unlock in game.
3) Finally, when the PlayerModel.php queried the player_unlock table for a valid timestamp it would then format the time using TimeSpan.php, something which was throwing an error in anything newer than PHP 7.3.x

**Comment by darth3pio** [comment]
On a side note, I've been taking a peek at BF2S Clone to get that up and running. Basically a bunch of deprecated queries to mysql instead of mysqli and updating sql queries to the 3.x.x schema rather than the older 2.x.x schema

**Comment by leojonathanoh** [comment]
Thanks for the detailed explanation. Just spun up a development environment, i see the exception is:

```
Error Description

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'timestamp' in 'field list'
Error Details

    Type: PDOException
    Code: 42S22
    File: /src/ASP/frontend/modules/players/models/PlayerModel.php
    Line: 928

Stack Trace

    /frontend/modules/players/models/PlayerModel.php @ line 928:
        PDO->query('SELECT `unlock_id`, `timestamp` FROM `player_unlock` WHERE `player_id`=2900000 ORDER BY `unlock_id` ASC')
    /frontend/modules/players/Players.php @ line 126:
        PlayerModel->attachUnlockData(2900000, System\View())
    (unknown file) @ line 0:
        Players->view(2900000)
    /system/System.php @ line 336:
        ReflectionMethod->invokeArgs(Players(), array(1))
    /system/System.php @ line 260:
        System::LoadModule('players', 'view', array(1))
    /system/System.php @ line 54:
        System::HandleAdminRequest()
    /index.php @ line 47:
        System::Run()

```

which like you explained is because of a missing column in `player_unlock` table in the `schema.sql`. So I guess this PR is correct that this should be a fix.

Don't see a point opening a separate PR just for fixing the deprecated syntax `$format{$o - 1}` for php >= 7.3.

But overall, spinning up the stack from scratch on this PR, the player view now works properly in stats admin. 

Just one little change. Could you prefix the PR title with `Fix: ...`, just to keep with conventional commits. Other than that it is good to go.

**Comment by leojonathanoh** [comment]
lgtm. Thanks for your contribution! 😄

**Pull request merged**
