### PR TITLE
Fix: DataTable jquery library throwing null value error upon table insert

### PR DESCRIPTION
**Pull request by darth3pio**
I suspect, unlike the awards.js table where user input prompts for an id, because the id for game mods is an autoincrement value in the game_mod database table the function isn't pulling down the new value upon insertion and complaining about a null value.

This is a possibly temporary fix until I can wrap my head around this specific problem and have ajax handle the table reload as seems to be the way it's handled in other pages within the gamedata module.

### CODE REVIEW

**Comment by leojonathanoh** [comment]
Thanks again! I'm not familiar with the ASP v3.0, so it's my first time using it, Just tried, i saw the error when adding a new game mod:

```
DataTables warning: table id=DataTables_Table_0 - Requested unknown parameter '0' for row 5, column 0. For more information about this error, please see http://datatables.net/tn/4
```

I might have found the bug, variable was misspelled for [`$data['id']`](https://github.com/startersclan/ASP/blob/e81ce1afe62ae2a90ca517d1156c210c033922f6/src/ASP/frontend/modules/gamedata/Gamedata.php#L611). After fixing the variable name, the `game_mod` does add a new entry without an error.

**Comment by darth3pio** [comment]
I'll take a look, if that fixes the issue then I'll resubmit.

**Comment by leojonathanoh** [comment]
sure :)

**Comment by darth3pio** [comment]
Uh, is this in Gamedata.php => postAddMod()?

I've been looking at this too long.

**Comment by darth3pio** [comment]
Uh... I'd already fixed it... "date"... These late night coding sessions are getting to me.

**Comment by darth3pio** [comment]
Will resubmit  with only the required changes.

**Pull request closed without merging**
