### PR TITLE
Fix: Spelling mistake of $date['id']; refrences to unlock instead of mod; varchar length

### PR DESCRIPTION
**Pull request by darth3pio**
- $date['id'] should be $data['id']
- Fixed references to unlocks in several comments and strings.
- varchar length in the database shows that name and longname in game_mod is 24 and 48 respectively, updated validator to reflect this.

### CODE REVIEW

**Comment by leojonathanoh** [comment]
yay, this looks good now :) Thanks!

**Review by leojonathanoh — APPROVED** [review]
lgtm

**Comment by darth3pio** [comment]
I figure Docker is a more convenient way to get it all up and running so contributing to this is contributing back into my locally hosted LAN server.

**Comment by leojonathanoh** [comment]
it's nice to know there's still a BF2 community, don't know what happened to bf2statistics.com community when I checked last week :(

**Comment by darth3pio** [comment]
Yeah, I noticed that, a bunch of Wilson's repos are gone too so I'm assuming he's maybe packed it in? Life stuff perhaps?

Hopefully we'll see him return and if not his legacy will go on.

**Comment by leojonathanoh** [comment]
yeah... The BF2Statistics github organization no longer owns the original fork, but the projects are now under ReviveNetwork. Feels like things have moved on. Hopefully there are developers like you that stick around github 😄

**Comment by leojonathanoh** [comment]
Just enabled the discussions tab on this repo, perhaps it can fill in something for the BF2Statistics community who use ASP v3 😃

**Comment by darth3pio** [comment]
For sure, I'll be sticking with it, a Git like this is perfect for contributing and sharing code and ideas if nothing else. And with modding still active as shown by all of the recent activity over at ModDB the need to have a backend to host it isn't going away.

My unrealised dream of course, as teased by several comments from Wilson over recent years is how easy it would allegedly be to get Battlefield 2142 support integrated. That's one of my longterm goals.

There's something about that era of Battlefield that has stayed with me.

**Comment by leojonathanoh** [comment]
Didn't know BF2142 could be integrated with this stats system? Perhaps the engines are almost the same? I've owned but didn't play 2142 much, so it's pretty much only BF2 for me 😝

**Comment by darth3pio** [comment]
Wilson bookmarked [imported Google Code repos] a bunch of stuff including (imported Google Code repos), https://github.com/wilson212/bf2142stats_emu, but it's a back of the queue sort of thing. Most of the work would be around the login side of things I suspect. Looking at the game server constants.py the structure looks similar enough that the stats database wouldn't need too much work.

**Comment by darth3pio** [comment]
More than anything, I wanna get back into the Star Wars: First Strike mod.

That thing was a heck of a lot of fun.

**Comment by leojonathanoh** [comment]
Cool stuff. Good thing the google code repos are automatically imported to github, or a lot of work would have been lost. Perhaps somebody might be bold enough to work on that 😀 

Those old games are a heck of fun. My fondest memories are with Counter-Strike, which is still going on strong 😛

**Comment by leojonathanoh** [comment]
By the way, from your recent testing, does ASP v3 work properly most of the time? I haven't been using ASP v3 so it'll be nice to know whether it really works, and haven't been following the BF2Statistics community in regard to ASP v3 too, so I don't know about the roadmaps / bugs / new features people were requesting.

At this point, if it's working, we might be able to cut a release for `v3.2.0`, the changelog's getting a bit too large. 😄

**Comment by leojonathanoh** [comment]
Nice information. At least from you described about most fixes already having been done, v3 should work without any major issue. So it should be fine to release `v3.2.0` in the next few days.

As for the planned v4, I assume there's no repo as it is, it was really just a roadmap / idea. It'll be kinda nice to see how ASP could fully replace the forums, in that case the soldier's BF2 in-game account would also be their forum account, with `bf2sclone` stats. The integration would be nice. 😄

**Comment by darth3pio** [comment]
It looked like something a little more than a roadmap, http://web.archive.org/web/20230209001842/https://bf2statistics.com/threads/update-3-2-incoming-and-php8-support-v4-0.3031/

**Comment by leojonathanoh** [comment]
Hmm seemed like it was being worked on actively, based on ASP v3 system. Hopefully the site comes back up, it was a great community 😢 if not, somebody to keep this going, we will see.

**Pull request merged**
